name: randomiser_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.6
  reactive_forms: ^16.1.1
  velocity_x: ^4.1.2
  path_provider: ^2.1.2
  path_provider_platform_interface: ^2.1.2
  auto_route: ^7.8.4
  equatable: ^2.0.5
  dartx: ^1.2.0
  dartz: ^0.10.1
  rxdart: ^0.27.7
  collection: ^1.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  responsive_framework: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  freezed: ^2.4.6
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
