name: Flutter Build
on:
  push:
    branches: [ master ]
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Upload iOS Build
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos
      - name: Upload macOS Build
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build/macos/Build/Products/Release
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows
      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/runner/Release
