name: Flutter Build
on:
  push:
    branches: [ master ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload Android APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: ./build/app/outputs/flutter-apk/app-release.apk
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Package .app as .ipa
        run: |
          mkdir Payload
          cp -r ./build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r build/ios/Runner.ipa Payload
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v2
        with:
          name: ios-ipa
          path: ./build/ios/Runner.ipa

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos
      - name: Create .dmg file
        run: |
          hdiutil create -volname "Randomiser App" -srcfolder ./build/macos/Build/Products/Release/ -ov -format UDZO randomiser_app_macOS_${{ github.run_number }}.dmg
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v2
        with:
          name: macos-dmg
          path: ./randomiser_app_macOS_${{ github.run_number }}.dmg
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v2
        with:
          name: windows-exe
          path: ./build/windows/x64/runner/Release/randomiser_app.exe

  create_release:
    needs: [build_android, build_ios, build_macos, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v2


      - name: Upload Android APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android-apk/app-release.apk
          asset_name: randomiser_app_Android_${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Upload iOS IPA
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ios-ipa/Runner.ipa
          asset_name: randomiser_app_iOS_${{ github.run_number }}.ipa
          asset_content_type: application/octet-stream

      - name: Upload macOS DMG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-dmg/randomiser_app_macOS_${{ github.run_number }}.dmg
          asset_name: randomiser_app_macOS_${{ github.run_number }}.dmg
          asset_content_type: application/x-diskcopy

      - name: Upload Windows EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-exe/randomiser_app.exe
          asset_name: randomiser_app_Windows_${{ github.run_number }}.exe
          asset_content_type: application/octet-stream

  publish_release:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android-apk/app-release.apk
            ios-ipa/Runner.ipa
            macos-dmg/randomiser_app_macOS_${{ github.run_number }}.dmg
            windows-exe/randomiser_app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          RELEASE_REPO: crovax124/randomiser



  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web
        run: flutter build web

  deploy_web:
    needs: [build_web]
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Web
        run: flutter build web
      - name: Copy web build to a different branch
        run: |
          git checkout -b web-deployment  # Create and switch to a new branch
          cp -r build/web/* ./
          git add .
          git commit -m "Deploy web version"
          git push -u origin web-deployment  # Push the changes to the new branch

